### ISSUE TITLE
sensor to understand when the washing is completed

### ISSUE THREAD

**Issue by sunsgs** [ollo69/ha-smartthinq-washer#10]
I have successfully installed this on HA. i can see only one sensor : sensor.washer
What is the sensor to understand when the wasing is completed?
Thanks

**Comment by ollo69** [comment]
You must use the sensor attributes, they are updated with washer information

**Comment by sunsgs** [comment]
Something like this ?

- alias: 'finished'
  trigger:
    platform: template
    value_template: '{{ state_attr('sensor.washer', 'run_completed') == 'on' }}'
  action:
    service: script.say
    data:
      message: finished

is that correct?

**Comment by ollo69** [comment]
yes, somewthing like this

**Comment by ollo69** [comment]
Close this issue, please use #13 for additional discussion about this point.
