### ISSUE TITLE
Only USA accounts can login

### ISSUE THREAD

**Issue by eld00fish** [ollo69/ha-smartthinq-washer#14]
I have a Canadian Google Play store (and therefore ThinqQ app) but the login url with the UI provides a US login. Is there any way to get a Canadian URL and use the redirection url to proceed?

Without this the Cell App won't work, which is more important to me anyways.

**Comment by ollo69** [comment]
Redirect URL is created by LG and not by the component. Do you login with social account or with a dedicated account?

**Comment by eld00fish** [comment]
I know that. I have created a dedicated ThinQ account, however it is a Canadian one, this is regional, it's not only US, and therefore when anyone non american tries to use your component (with the US login url that the component provides), it won't work. Google Play provides a regional Canadian app.

I have created a US account using the url provided by the component, however I'm unable to login with the Canadian app to use it to sync the appliances (It specifically states that it's a American account that was used to create it, and vice versa when using a Canadian login in the component url).

I thought this script was very cool, so I thought I'd give the heads up in case you wanted a non-US tester. Either way, thanks for the amazingly fast reply.

Cheers man!

**Comment by Golab** [comment]
No problem and I’m using my Swedish account when I login it makes a redirect to https://kr.m.lgaccount.com/login/iabClose?state

**Comment by ollo69** [comment]
> I know that. I have created a dedicated ThinQ account, however it is a Canadian one, this is regional, it's not only US, and therefore when anyone non american tries to use your component (with the US login url that the component provides), it won't work. Google Play provides a regional Canadian app.
> 
> I have created a US account using the url provided by the component, however I'm unable to login with the Canadian app to use it to sync the appliances (It specifically states that it's a American account that was used to create it, and vice versa when using a Canadian login in the component url).
> 
> I thought this script was very cool, so I thought I'd give the heads up in case you wanted a non-US tester. Either way, thanks for the amazingly fast reply.
> 
> Cheers man!

Is not clear to me your problem, don't know if there are some specific issue related to Canada.
My account is Italian, so at the begining it use `it-IT` for language and `IT` for region. I suppose you should use `en-CA` and `CA`, not sure about this.
For sure LG account is connected to the language so if you use USA code does not work.

**Comment by eld00fish** [comment]
en-US works, I tried again and it's not giving me the error today. I must have been tired last night and did something stupid as I can't replicate. Thank you for your time, going to get this going for my washer\drier.

**Comment by Golab** [comment]
I had a problem when I tried to get Alexa to work whit my ThingQ account because I live in Sweden and LGs Alexa support I sent supported one Sweden, tried to move my washing machine to a US account, when I moved my machine to us account it showed status that my machine was turned off, even when it was turned on and connected to internet I needed to Wait something line 6 hours + for my machine to show status online,

can it be that problem he is getting when he from Canada account to US account?

Anyway I could not get Alexa to work but Google Home works great
