### ISSUE TITLE
Obtaining token

### ISSUE THREAD

**Issue by daveonkels** [ollo69/ha-smartthinq-washer#2]
Incredibly excited to see this integration being built. Any tips on obtaining an access token? For reference, I created an account at https://thinqcloud.developer.lge.com/ but can only seem to find an account management screen.

**Comment by ollo69** [comment]
Hi,

you should follow the integration setup instruction  using UI, it will guide you in the token creation.
Pls try and let me know.

**Comment by daveonkels** [comment]
I was clearly overthinking it, getting connected worked like a champ. Now the problem is I don't see my washer (or dryer or dishwasher for that matter - but would expect that). Does this relate to #1 ?

**Comment by ollo69** [comment]
This manage only washer, at least for the moment.
Bur you should see the washer, probably you will have some error but only during run.
If the Washer sensor is not created, please check your log and post errors.

**Comment by ollo69** [comment]
Please test last release and let me know.
Refer also to issue #1

**Comment by ollo69** [comment]
Did you manage component configuration?

**Comment by macguy81** [comment]
> Did you manage component configuration?

I am not able to generate a token, i keep getting error message saying invalid credentials, i have a Thinq app signed using google account, it did not work so i tried create a brand new account with email. When i use that i comes back with token but when i submit it say invalid credentials.

**Comment by daveonkels** [comment]
Got it to work - followed your instructions to recreate the account with a social media login. Appreciate you working so hard to track down these issues @ollo69 - I've been so eager to get these LG devices into HA.

**Comment by ollo69** [comment]
May be API2 works also with social media login, but I didn't test it. I close this issue.
