### ISSUE TITLE
LG Dryer

### ISSUE THREAD

**Issue by pigmos** [ollo69/ha-smartthinq-washer#5]
Is there a way to add also a LG Dryer?

**Comment by ollo69** [comment]
Yes, in the future I will work to add additional sensor.

**Comment by pigmos** [comment]
I think that if I can modify your work I can create a new component that works wth dryers. But I don't know where I have to modify your work. If you can help me, i can so that, so after you can integrate ina  single component.
P.S. Excuse me for my poor english.

**Comment by ollo69** [comment]
First of all you must create a fork of this project on your git account, then you can modify the code and then submit a Pull Request to main repository. Then I will check your change and merge to main repository.
But take in consideration that I'm working on this project so you can create conflict. Start explaining what you would like to do.

**Comment by ollo69** [comment]
I just released Dryer support, test can start now. Please provide feed-back and send to me logs (possible debug), because not having Dryer I wasn't able to do any test.

**Comment by pigmos** [comment]
Ok, I test it just now.
