### ISSUE TITLE
Additional attribute: remain_time_in_minutes

### ISSUE THREAD

**Issue by dieneuser** [ollo69/ha-smartthinq-washer#7]
Hello,

is it possible to add an attribute: remain_time_in_minutes? I need this value for the lovelace ui for the custom:circle-sensor-card. And it would be easier for calculations in automations.

THX

**Comment by ollo69** [comment]
You should use platform template for this, or I will add an infinite numbers of attributes.
Here an example (assuming that the name of your washer is "washer"):

```
sensor:
  - platform: template
    
    sensors:

      washer_remain_time_in_minutes:
        friendly_name: Remaining Minutes
        value_template: >-
          {% if is_state('sensor.washer', 'on') %}
          {{(state_attr('sensor.washer', 'remain_time').split(':')[0]|int*60) + 
            (state_attr('sensor.washer', 'remain_time').split(':')[1]|int)
           }}
          {%endif%}
```

**Comment by dieneuser** [comment]
Thank you for the solution. This code is how I did it for the automation script. The solution with the sensor is perfect and I can use the locelace circle card.

**Comment by sunsgs** [comment]
Hi @dieneuser can you please share how you used it into automations?
