### ISSUE TITLE
The condition of the washing machine is not visible

### ISSUE THREAD

**Issue by KrzysiekLegnica** [ollo69/ha-smartthinq-washer#8]
Integration Hass.io cannot see the washing machine. The APIv2 version sees the washing machine but cannot see its status.  (Washer F_R7_D___W.A__QEUK-FL (MAC: 60:ab:14:xx:xx:xx)
producent: LG

**Comment by ollo69** [comment]
Hi, please refer on issue #3, this is a now problem and connot be fixed shortly.

**Comment by ollo69** [comment]
I close this issue because solved, for question use documentation or refer to discussion at issue #3
