### ISSUE TITLE
Notification upon load completion

### ISSUE THREAD

**Issue by daveonkels** [ollo69/ha-smartthinq-washer#9]
Anyone have an example YAML or Node-Red of how you're detecting when the load is complete? I'd like to send a notification over my Alexa devices.

**Comment by ollo69** [comment]
There is a boolead attribute called "wash_completed"(or "run_completed in version 0.2.x) for this.
Caution because I just changed "wash_completed" to "run_completed" with last release 0.2.0 to properly manage the attribute for different devices type

**Comment by daveonkels** [comment]
Fantastic, that will work nicely.

**Comment by sunsgs** [comment]
Hi @daveonkels can you please share how u implemented the run_completed boolean?
pretty new on ha and i see only a sensor for the wasing machine

**Comment by daveonkels** [comment]
Sure, I'll whip up a version of this after work now that I know how to get it done. The key is to monitor for changes to the underlying attribute, in this case 'run_completed' but since that's an attribute from the main payload it's a bit harder to fetch.

**Comment by ollo69** [comment]
Close this issue, please use #13 for additional discussion about this point.
